version: "3.7"

services:
  order-consumer:
    build: ./docker/consumer
    container_name: order-consumer
    environment:
      - TOPIC=order-received
    depends_on:
      - broker
    networks:
      - ppe

  order:
    build:
      dockerfile: ./docker/order/Dockerfile
      context: .
    container_name: order
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      timeout: 10s
      retries: 3
    depends_on:
      - broker
    networks:
      - ppe

networks:
  ppe:
    name: ppe
